# colors
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
BLACK = (0, 0, 0)
YELLOW = (255, 255, 0)
PINK = (255, 105, 180)
PURPLE = (128, 0, 128)
ORANGE = (120,120,0)

# title settings
TITLE_MARGIN_TOP = 10

# random dot generator
RECT_SIZE = 200
DOT_NUMBER = 6

# algo settings
NAIVE_TRIANGULATION_BACKGROUND_COLOR = BLUE
SLOW_DELAUNAY_BACKGROUND_COLOR = ORANGE

# dot settings
DOT_SIZE = 2
DOT_COLOR = YELLOW
SELECTED_DOT_COLOR = BLACK
SELECTED_DOT_BORDER_SIZE = 2

# triangle settings
SELECTED_TRIANGLE_COLOR = BLACK
TRIANGLE_COLOR = RED
TRIANGLE_LINE_SIZE = 2
SELECTED_TRIANGLE_BORDER_SIZE = 2


# polygon settings
POLYGON_COLOR = PINK
POLYGON_LINE_WIDTH = 2

# segment settings
DEFAULT_SEGMENT_SIZE = 100
SEGMENT_COLOR = PURPLE
SEGMENT_WIDTH = 6
